using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DataAccess;
using System.Data.Entity;
using DevExpress.XtraEditors.Repository;

namespace MovieManager
{
    public partial class MovieForm : Form
    {
        private BindingSource movieGridViewModelBindingSource;
        private DevExpress.XtraGrid.GridControl gridControl1;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private MovieManagerEntities dbContext = new MovieManagerEntities();
        public MovieForm()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Uncomment next line to set the total number of data records stored within your source
            // unboundSource1.SetRowCount(42);
            // This line of code is generated by Data Source Configuration Wizard

          
        }


        private void buttonAdd_Click(object sender, EventArgs e)
        {
            MessageBox.Show("Record Inserted Successfully");
        }

        private void MovieForm_Load(object sender, EventArgs e)
        {
            var moviesGridViewModel = (from movie in dbContext.Movie
                                       select new MovieGridViewModel()
                                       {
                                           Title = movie.Title,
                                           Watched = movie.Watched.Any(),
                                           WatchList = movie.WatchList.Any()
                                       }).ToList();

            BindingList<MovieGridViewModel> list = new BindingList<MovieGridViewModel>(moviesGridViewModel);

            movieGrid.DataSource = list;

            //var populateGenre = from genre in dbContext.Genre
            //                    select genre.GenreType. ToString();

            //foreach (var gen in populateGenre)
            //{
            //    repositoryItemComboBox1.Items.Add(gen);

            //}

            //movieGrid.

        }


        private void buttonSave_Click(object sender, EventArgs e)
        {
            dbContext.SaveChanges();
        }

       

      
        private void buttonDelete_Click(object sender, EventArgs e)
        {


        }

        private void movieGrid_Click(object sender, EventArgs e)
        {


         


        }



        private void gridView1_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {

          

        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            var test = sender as DevExpress.XtraGrid.Views.Grid.GridView;
            test.GetSelectedRows();
            //test.GetFocusedRowCellValue();



            //textBoxID.Text = test.GetRowCellValue(e.FocusedRowHandle, "MovieId").ToString();
                        
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValueNeeded(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {

            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValuePushed(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {

            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }

        private void InitializeComponent()
        {
            this.movieGridViewModelBindingSource = new System.Windows.Forms.BindingSource();
            this.gridControl1 = new DevExpress.XtraGrid.GridControl();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            ((System.ComponentModel.ISupportInitialize)(this.movieGridViewModelBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // movieGridViewModelBindingSource
            // 
            this.movieGridViewModelBindingSource.DataSource = typeof(MovieManager.MovieGridViewModel);
            // 
            // gridControl1
            // 
            this.gridControl1.Location = new System.Drawing.Point(457, 157);
            this.gridControl1.MainView = this.gridView1;
            this.gridControl1.Name = "gridControl1";
            this.gridControl1.Size = new System.Drawing.Size(400, 200);
            this.gridControl1.TabIndex = 0;
            this.gridControl1.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView1});
            // 
            // gridView1
            // 
            this.gridView1.GridControl = this.gridControl1;
            this.gridView1.Name = "gridView1";
            // 
            // MovieForm
            // 
            this.ClientSize = new System.Drawing.Size(1010, 467);
            this.Controls.Add(this.gridControl1);
            this.Name = "MovieForm";
            this.Load += new System.EventHandler(this.MovieForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.movieGridViewModelBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            this.ResumeLayout(false);

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

    }
}

