//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMovieManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieManagerEntities : DbContext
    {
        public MovieManagerEntities()
            : base("name=MovieManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Cast> Casts { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Watched> Watched { get; set; }
        public virtual DbSet<WatchList> WatchList { get; set; }
    }
}
