//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMovieManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watched:Movie
    {
       public int WatchedId { get; set; }
      //  public int MovieId { get; set; }
        public Nullable<bool> Favourite { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
